'use client';
import { useEffect, useState } from 'react';
import InternshipCard from './internship-card';
import { ArrowUpRight, ArrowRight, BookOpen, Check, Code2, FileCheck2, GraduationCap, LifeBuoy, Mail, ShieldCheck, Sparkles } from 'lucide-react';
const steps = [
    { title: 'Find your direction', label: 'Choose & apply', icon: BookOpen, text: 'Explore a track that interests you. Apply with your goals and preferred start date, then wait for your application review.', preview: 'A path that fits your curiosity', items: ['Explore free courses and task briefs', 'Choose your internship track', 'Receive your offer after approval'] },
    { title: 'Learn it. Then build it.', label: 'Learn & build', icon: Code2, text: 'Follow curated courses and turn each concept into a real project. Start with the basics, then unlock the next level through approved work.', preview: 'Small projects. Real progress.', items: ['Beginner: get the foundations right', 'Intermediate: connect your skills', 'Advanced: build your capstone'] },
    { title: 'Show the work behind it', label: 'Submit & improve', icon: FileCheck2, text: 'Share your repository, notes, and supporting evidence. Receive a review, use the feedback, and resubmit when changes are needed.', preview: 'Your work tells the story', items: ['Share original code and a clear README', 'Explain how you tested your project', 'Get feedback and verified progress'] },
    { title: 'Make your progress visible', label: 'Complete & celebrate', icon: GraduationCap, text: 'After every required project and final completion approval, you can claim your free certificate with a public verification page.', preview: 'Recognition you can point to', items: ['Complete all required projects', 'Receive final program approval', 'Claim your free verified certificate'] }
];
const faqs = [
    ['Is it free to join?', 'Yes. Applying, accessing learning resources, and building projects are free. Your completion certificate is also free and unlocks after your work is verified.'],
    ['How do I start?', 'Explore the tracks and public task briefs, create an account, and apply. Your application must be approved before you can submit projects or receive an offer letter.'],
    ['What if my project needs changes?', 'Read the reviewer feedback in your workspace, improve the project, and resubmit. The next level unlocks when every required project in the previous level is approved.'],
    ['How do I get my free certificate?', 'Complete the required projects and receive final approval, then select Get free certificate in your workspace. No payment details are needed.'],
    ['Is this a job or a job guarantee?', 'This is a project-based virtual learning internship. Participation does not create an employment relationship or guarantee a job. Your completed projects help demonstrate your skills.']
];
export function Support() {
    return <section className="container intro-support" id="support"><div className="support-copy"><span className="intro-kicker"><LifeBuoy size={16}/> CUSTOMER SUPPORT</span><h2>A little help.<br />A clearer next step.</h2><p>Questions about applications, projects, or certificates? Start here.</p><div className="support-contact"><Mail size={24}/><h3>Chat with our guide</h3><p>Get instant guidance on applications, submissions, and certificates in our automated support chat.</p><button className="secondary" onClick={() => window.dispatchEvent(new Event('samkov-support'))}>Open support chat <ArrowUpRight size={16}/></button></div></div><div className="intro-faq">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>;
}
export default function Home({ go, tracks }) {
    const [step, setStep] = useState(0);
    const [reducedMotion, setReducedMotion] = useState(false);
    const [interacting, setInteracting] = useState(false);
    useEffect(() => {
        const preference = window.matchMedia('(prefers-reduced-motion: reduce)');
        const update = () => setReducedMotion(preference.matches);
        update();
        preference.addEventListener('change', update);
        return () => preference.removeEventListener('change', update);
    }, []);
    useEffect(() => {
        if (reducedMotion || interacting) return;
        const timer = setInterval(() => {
            if (document.visibilityState === 'visible') setStep(value => (value + 1) % steps.length);
        }, 6000);
        return () => clearInterval(timer);
    }, [step, reducedMotion, interacting]);
    const current = steps[step];
    const Icon = current.icon;
    return <main className="intro-home"><section className="container intro-hero"><div><span className="intro-kicker"><span className="live-dot"/> THE SPACE BETWEEN LEARNING & DOING</span><h1>You bring the curiosity.<br /><span>Build what comes next.</span></h1><p>SamkovAI turns online learning into hands-on experience. Follow a guided internship, build real projects, and leave with work that shows what you can do.</p><div className="hero-actions"><button className="primary" onClick={() => go('/internships')}>Find your path <ArrowUpRight size={18}/></button><a className="secondary" href="#how-it-works">See how it works <ArrowRight size={17}/></a></div><div className="intro-promises"><span><Check size={15}/>Free to learn</span><span><Check size={15}/>Projects with purpose</span><span><Check size={15}/>Reviewed by people</span></div></div><div className="intro-visual"><div className="intro-orbit" aria-hidden="true"/><div className="hero-cube" aria-hidden="true"><i /><i /><i /><i /><i /><i /></div><span className="hero-float-tag" aria-hidden="true">&lt;build your future /&gt;</span><div className="build-board"><div className="board-top"><span><i /><i /><i /></span><small>YOUR NEXT CHAPTER</small><Sparkles size={16}/></div><div className="board-body"><span className="board-tag">FROM IDEA TO “I BUILT THIS”</span><h2>Less wondering.<br />More creating.</h2><div className="board-project"><span className="board-project-icon"><Code2 size={26}/></span><div><small>YOUR FIRST PROJECT</small><strong>Something worth sharing.</strong></div><ArrowUpRight size={20}/></div><div className="board-path"><span><Check size={12}/> Learn</span><i /><span><Code2 size={12}/> Build</span><i /><span><ShieldCheck size={12}/> Prove</span></div><div className="board-code"><span>01</span> curiosity + consistent practice<br /><span>02</span> <b>→ skills you can demonstrate</b></div></div><div className="board-bottom"><span className="live-dot"/>Your pace. Your progress. Your proof.</div></div><div className="intro-sticker"><ShieldCheck size={23}/><span>Earned through effort.<small>Backed by real work.</small></span></div></div></section>
 <section className="intro-strip"><div className="container"><span>A clear path, from your first question to your final project.</span><b>LEARN <ArrowRight size={14}/> BUILD <ArrowRight size={14}/> GET REVIEWED <ArrowRight size={14}/> GROW</b></div></section>
 <section className="container intro-about"><div><span className="intro-kicker">WHAT IS SAMKOVAI?</span><h2>A place to turn<br />“I know it” into<br /><span>“I can do it.”</span></h2></div><div><p className="intro-lead">Courses give you a starting point. Building gives you experience.</p><p>We bring learning resources, a structured project roadmap, and submission reviews into one workspace. You focus on making things; your roadmap keeps the next step clear.</p><div className="intro-value-grid">{[[BookOpen, 'Guidance, without the guesswork', 'Curated resources and clear task briefs.'], [Code2, 'A portfolio built by you', 'Original projects you can explain and share.'], [ShieldCheck, 'Progress you can prove', 'Reviewed work and verifiable completion.']].map(([I, title, text]) => <article key={title}><I size={21}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="intro-process" id="how-it-works"><div className="container"><div className="intro-section-top"><div><span className="intro-kicker">HOW IT WORKS</span><h2>One next step.<br />A whole new skill set.</h2></div><p>From choosing your track to sharing your achievement.<br />Here’s what your journey looks like.</p></div><div className="intro-process-grid" onMouseEnter={() => setInteracting(true)} onMouseLeave={() => setInteracting(false)} onFocus={() => setInteracting(true)} onBlur={event => { if (!event.currentTarget.contains(event.relatedTarget)) setInteracting(false); }}><div className="process-steps" role="tablist" aria-label="Internship journey">{steps.map((s, i) => <button key={s.label} id={'step-' + i} role="tab" aria-selected={step === i} aria-controls="journey-panel" tabIndex={step === i ? 0 : -1} onKeyDown={e => { if (['ArrowDown', 'ArrowUp', 'ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) {
        e.preventDefault();
        const next = e.key === 'Home' ? 0 : e.key === 'End' ? 3 : (step + (['ArrowDown', 'ArrowRight'].includes(e.key) ? 1 : 3)) % 4;
        setStep(next);
        document.getElementById('step-' + next)?.focus();
    } }} className={step === i ? 'process-step selected' : 'process-step'} onClick={() => setStep(i)}><span>0{i + 1}</span><div><small>{s.label}</small><h3>{s.title}</h3></div><ArrowUpRight size={20}/></button>)}</div><article id="journey-panel" role="tabpanel" aria-labelledby={'step-' + step} className="process-preview"><div className="process-preview-top"><Icon size={30}/><span>STEP 0{step + 1} / 04</span></div><h3>{current.preview}</h3><p>{current.text}</p><ul>{current.items.map(item => <li key={item}><Check size={16}/>{item}</li>)}</ul><div className="process-slide-controls"><div className="process-dots">{steps.map((s, i) => <button key={s.label} aria-label={'Show step ' + (i + 1) + ': ' + s.label} aria-pressed={step === i} onClick={() => setStep(i)} className={step === i ? 'active' : ''}/>)}</div></div></article></div></div></section>
 <section className="container intro-paths"><span className="intro-kicker">A DIRECTION FOR YOUR AMBITION</span><h2>Find the thing you want to build.</h2><p>Start with a subject that sparks your interest. Explore its courses and projects before applying.</p><div className="track-grid home-track-grid">{tracks.map(t => <InternshipCard key={t.slug} track={t} go={go}/>)}</div></section>
 <section className="container intro-proof"><div className="proof-symbol"><GraduationCap size={52}/></div><div><span className="intro-kicker">YOUR EFFORT IS THE IMPORTANT PART</span><h2>Free to learn.<br />Recognition when you’re ready.</h2><p>Apply, learn, and build for free. After all your projects and final completion are approved, claim your free certificate with its own verification ID and QR code.</p><button className="text-link" onClick={() => go('/verify')}>Explore certificate verification <ArrowRight size={16}/></button></div><div className="intro-price"><span>VERIFIED CERTIFICATE</span><strong>Free</strong><small>Included · after verified completion</small></div></section>
 <Support /><section className="container intro-last"><span className="intro-kicker">START WHERE YOU ARE</span><h2>Your next chapter<br />starts with one project.</h2><button className="primary" onClick={() => go('/internships')}>Let’s find your path <ArrowUpRight size={18}/></button><p>No payment to apply. Just a little curiosity.</p></section></main>;
}
