export type VideoResource={title:string;url:string;language:'English'|'Hindi'|'Tamil';kind:'Playlist'|'Video';source:string};
const source=(slug:string)=>'https://www.nexlevr.app/resources/'+slug;
const v=(title:string,url:string,language:VideoResource['language'],slug:string):VideoResource=>({title,url,language,kind:url.includes('playlist')?'Playlist':'Video',source:source(slug)});
// Links observed on Nexlevr's public resource pages on 2026-09-17. Content remains with its creators.
export const videos:Record<string,VideoResource[]>={
 python:[v('Python Complete Course','https://youtube.com/playlist?list=PLsyeobzWxl7omDoEYrrf3oXvXxa6MPgek','English','python-development'),v('Python Full Tutorial','https://youtu.be/nLRL_NcnK-4','English','python-development'),v('Python Full Course','https://youtu.be/UrsmFxEIp5k','Hindi','python-development'),v('Python Tutorial','https://youtu.be/HAxm8n9QY50','Tamil','python-development'),v('Python Complete Guide','https://youtu.be/QGAuolgCTHE','Tamil','python-development')],
 'machine-learning':[v('Stanford ML Course','https://youtube.com/playlist?list=PLoROMvodv4rMiGQp3WXShtMGgzqpfVfbU','English','machine-learning'),v('ML Full Course','https://youtu.be/JxgmHe2NyeY','English','machine-learning'),v('Machine Learning Course','https://youtube.com/playlist?list=PLaldQ9PzZd9qT0KsKJ7yCq70iFFP3MFJ5','Hindi','machine-learning'),v('ML with Python','https://youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH','Hindi','machine-learning')],
 'data-science':[v('Data Science Tutorial','https://youtu.be/LZzq1zSL1bs','English','data-science'),v('Data Science Full Course','https://youtu.be/k6HOBjkUkE4','Tamil','data-science')],
 'data-analytics':[v('Data Analyst Full Course','https://youtu.be/eC9Z1QyJzSY','English','data-analyst'),v('SQL for Data Analysis','https://youtu.be/JtaOmwnR6AM','Tamil','data-analyst')],
 'artificial-intelligence':[v('AI Engineer Roadmap','https://youtu.be/rV3HJ4LEZ7k','English','ai-engineer'),v('CS50 AI with Python','https://youtube.com/playlist?list=PLhQjrBD2T381PopUTYtMSstgk-hsTGkVm','English','ai-engineer'),v('Python for AI','https://youtu.be/_aWbUudZ5Yo','English','ai-engineer')],
 'generative-ai':[v('Stanford NLP Course','https://youtube.com/playlist?list=PLoROMvodv4rObv1FMizXqumgVVdzX4_05','English','ai-llm-fundamentals'),v('LLM Fundamentals','https://youtu.be/zjkBMFhNj_g','English','ai-llm-fundamentals'),v('AI Crash Course','https://youtu.be/7xTGNNLPyMI','English','ai-llm-fundamentals'),v('Transformers Explained','https://youtu.be/LrVw2LtJsYw','English','ai-llm-fundamentals')],
 cybersecurity:[v('Cybersecurity Full Course','https://youtu.be/9HOpanT0GRs','English','cybersecurity'),v('Cybersecurity for Beginners','https://youtu.be/U_P23SqJaDc','English','cybersecurity'),v('CompTIA Security+ Course','https://youtube.com/playlist?list=PLG49S3nxzAnlCJiCrOYuRYb6cne864a7G','English','cybersecurity')],
 'web-development':[v('Full Stack Development Roadmap','https://youtu.be/LzMnsfqjzkA','English','full-stack-developer'),v('Full Stack Projects','https://youtube.com/playlist?list=PL6QREj8te1P7faGPL2hfiM8F9zdOvZpbF','English','full-stack-developer'),v('Full Stack Development Course','https://youtube.com/playlist?list=PLQEaRBV9gAFsistSzOgnD4cWgFGRVda4X','Hindi','full-stack-developer'),v('Full Stack Web Development','https://youtube.com/playlist?list=PLu0W_9lII9agq5TrH9XLIKQvv0iaF2X3w','Hindi','full-stack-developer'),v('Full Stack Developer Path','https://youtube.com/playlist?list=PLhP5RsB7fhE0bq7uHVsKAZcczgymmngTP','Tamil','full-stack-developer'),v('HTML & CSS Complete Course','https://youtube.com/playlist?list=PLYM2_EX_xVvXZ2A08faQ_7Iz4unlGs176','Tamil','full-stack-developer'),v('JavaScript Complete Course','https://youtube.com/playlist?list=PLYM2_EX_xVvWA3nMtsoLclwDtVS_rLk6O','Tamil','full-stack-developer')]
};
